// ---------------------------------------------------------------------------
// Config + .env generation — shared by the HTTP server and any future caller
// ---------------------------------------------------------------------------

import fs from 'fs-extra';
import path from 'node:path';
import { PROVIDERS, type ProviderId } from '@selfcure/generator';

export const FRAMEWORK_EXTENSIONS: Record<string, string[]> = {
  react: ['**/*.tsx', '**/*.jsx'],
  vue: ['**/*.vue'],
  angular: ['**/*.component.ts', '**/*.component.html'],
  auto: ['**/*.html'],
};

export interface InitAIOptions {
  provider: ProviderId;
  generationModel: string;
  healingModel: string;
  /**
   * API key value entered by the user. When empty AND `useExistingEnv` is
   * true, the server reads the value from its own process.env (so the key
   * never crosses the wire from the browser).
   */
  apiKey: string;
  /** Reuse the env var already set in the server's environment */
  useExistingEnv: boolean;
  /** Override the default endpoint — used for Ollama / DeepSeek / self-hosted */
  baseURL?: string;
}

export interface InitOptions {
  rootDir: string;
  /** 'react' | 'vue' | 'angular' | 'auto' */
  framework: string;
  /** Glob patterns to include — defaults to FRAMEWORK_EXTENSIONS[framework] when empty */
  include: string[];
  testsDir: string;
  baseURL: string;
  /** AI provider configuration */
  ai: InitAIOptions;
}

export interface GenerateResult {
  configContent: string;
  configPath: string;
  /** Reminder message — the actual key is never returned */
  envNote: string;
}

export function buildConfigContent(options: InitOptions): string {
  const { rootDir, framework, include, testsDir, baseURL, ai } = options;
  const safeInclude =
    include.length > 0
      ? include
      : (FRAMEWORK_EXTENSIONS[framework] ?? ['**/*.tsx']);
  const baseURLLine = ai.baseURL ? `\n    baseURL: '${ai.baseURL}',` : '';

  return `\
// selfcure.config.mjs — generated by selfcure init
/** @type {import('@selfcure/cli').SelfcureConfig} */
export default {
  // ── Source crawl ─────────────────────────────────────────────────────────
  rootDir: '${rootDir}',
  include: ${JSON.stringify(safeInclude)},
  exclude: ['**/*.spec.*', '**/*.test.*', '**/node_modules/**', '**/dist/**'],
  framework: '${framework}',

  // ── Authentication ────────────────────────────────────────────────────────
  // auth: { type: 'form', loginURL: '/login', ... },

  // ── Browser ──────────────────────────────────────────────────────────────
  browser: {
    type: 'chromium',
    headless: true,
    viewport: { width: 1280, height: 720 },
    timeout: 30_000,
    slowMo: 0,
  },

  // ── AI provider ──────────────────────────────────────────────────────────
  ai: {
    provider: '${ai.provider}',
    generationModel: '${ai.generationModel}',
    healingModel: '${ai.healingModel}',${baseURLLine}
  },

  // ── Test generation ───────────────────────────────────────────────────────
  testsDir: '${testsDir}',
  maxInputTokens: 4096,

  // ── Test execution ────────────────────────────────────────────────────────
  playwrightConfig: './playwright.config.ts',
  baseURL: '${baseURL}',

  // ── Self-healing ──────────────────────────────────────────────────────────
  maxHealAttempts: 3,

  // ── Reporting ─────────────────────────────────────────────────────────────
  reportDir: './selfcure-report',
  reportTitle: 'Selfcure Report',
};
`;
}

/**
 * Write selfcure.config.mjs and .env to {@link cwd}.
 *
 * The API key is resolved server-side:
 *   - if `ai.useExistingEnv` is true → read from this process's env
 *   - otherwise → use the value posted in `ai.apiKey`
 *
 * Ollama (no envVar) skips the .env update entirely.
 *
 * Returns the generated config content (the API key is NEVER included in the
 * return value).
 */
export async function generateConfig(
  options: InitOptions,
  cwd: string,
): Promise<GenerateResult> {
  const configContent = buildConfigContent(options);
  const configPath = path.join(cwd, 'selfcure.config.mjs');

  await fs.outputFile(configPath, configContent, 'utf-8');

  const meta = PROVIDERS[options.ai.provider];
  let envNote = 'No .env update required for this provider.';

  if (meta.envVar) {
    const value = options.ai.useExistingEnv
      ? (process.env[meta.envVar] ?? '')
      : options.ai.apiKey;

    if (value) {
      await upsertEnvVar(path.join(cwd, '.env'), meta.envVar, value);
      envNote = options.ai.useExistingEnv
        ? `.env updated from existing $${meta.envVar} in your environment (value omitted from this response).`
        : `.env written with ${meta.envVar} (value omitted from this response).`;
    } else {
      envNote =
        `No value available for ${meta.envVar}. Set it in your shell or rerun the wizard with a key.`;
    }
  }

  return {
    configContent,
    configPath,
    envNote,
  };
}

/**
 * Update or append a KEY=value line in a .env file without clobbering other
 * existing entries.
 */
async function upsertEnvVar(envPath: string, key: string, value: string): Promise<void> {
  let existing = '';
  try {
    existing = await fs.readFile(envPath, 'utf-8');
  } catch {
    // file doesn't exist yet — fine
  }

  const lineRegex = new RegExp(`^${key}=.*$`, 'm');
  const newLine = `${key}=${value}`;
  const updated = lineRegex.test(existing)
    ? existing.replace(lineRegex, newLine)
    : (existing.endsWith('\n') || existing === '' ? existing : existing + '\n') + newLine + '\n';

  await fs.outputFile(envPath, updated, 'utf-8');
}
