// ---------------------------------------------------------------------------
// Config + .env generation — shared by the HTTP server and any future caller
// ---------------------------------------------------------------------------

import fs from 'fs-extra';
import path from 'node:path';

export const FRAMEWORK_EXTENSIONS: Record<string, string[]> = {
  react: ['**/*.tsx', '**/*.jsx'],
  vue: ['**/*.vue'],
  angular: ['**/*.component.ts', '**/*.component.html'],
  auto: ['**/*.html'],
};

export interface InitOptions {
  rootDir: string;
  /** 'react' | 'vue' | 'angular' | 'auto' */
  framework: string;
  /** Glob patterns to include — defaults to FRAMEWORK_EXTENSIONS[framework] when empty */
  include: string[];
  testsDir: string;
  baseURL: string;
  /** Anthropic API key — written to .env, never returned in responses */
  apiKey: string;
}

export interface GenerateResult {
  configContent: string;
  configPath: string;
  /** Reminder message — the actual key is never returned */
  envNote: string;
}

export function buildConfigContent(options: InitOptions): string {
  const { rootDir, framework, include, testsDir, baseURL } = options;
  const safeInclude =
    include.length > 0
      ? include
      : (FRAMEWORK_EXTENSIONS[framework] ?? ['**/*.tsx']);

  return `\
// selfcure.config.js — generated by selfcure init
/** @type {import('@selfcure/cli').SelfcureConfig} */
export default {
  // ── Source crawl ─────────────────────────────────────────────────────────
  rootDir: '${rootDir}',
  include: ${JSON.stringify(safeInclude)},
  exclude: ['**/*.spec.*', '**/*.test.*', '**/node_modules/**', '**/dist/**'],
  framework: '${framework}',

  // ── Authentication ────────────────────────────────────────────────────────
  // auth: { type: 'form', loginURL: '/login', ... },

  // ── Browser ──────────────────────────────────────────────────────────────
  browser: {
    type: 'chromium',
    headless: true,
    viewport: { width: 1280, height: 720 },
    timeout: 30_000,
    slowMo: 0,
  },

  // ── Test generation ───────────────────────────────────────────────────────
  testsDir: '${testsDir}',
  generationModel: 'claude-opus-4-5',
  maxInputTokens: 4096,

  // ── Test execution ────────────────────────────────────────────────────────
  playwrightConfig: './playwright.config.ts',
  baseURL: '${baseURL}',

  // ── Self-healing ──────────────────────────────────────────────────────────
  healingModel: 'claude-haiku-3-5',
  maxHealAttempts: 3,

  // ── Reporting ─────────────────────────────────────────────────────────────
  reportDir: './selfcure-report',
  reportTitle: 'Selfcure Report',
};
`;
}

/**
 * Write selfcure.config.js and .env to {@link cwd}.
 * Returns the generated config content (the API key is NOT included in the return value).
 */
export async function generateConfig(
  options: InitOptions,
  cwd: string,
): Promise<GenerateResult> {
  const configContent = buildConfigContent(options);
  const configPath = path.join(cwd, 'selfcure.config.js');

  await fs.outputFile(configPath, configContent, 'utf-8');
  await fs.outputFile(
    path.join(cwd, '.env'),
    `ANTHROPIC_API_KEY=${options.apiKey}\n`,
    'utf-8',
  );

  return {
    configContent,
    configPath,
    envNote: '.env written with ANTHROPIC_API_KEY (value omitted from this response)',
  };
}
