// ---------------------------------------------------------------------------
// Config + .env generation — shared by the HTTP server and any future caller
// ---------------------------------------------------------------------------

import fs from 'fs-extra';
import path from 'node:path';
import { PROVIDERS, type ProviderId } from '@selfcure/generator';

export const FRAMEWORK_EXTENSIONS: Record<string, string[]> = {
  react: ['**/*.tsx', '**/*.jsx'],
  vue: ['**/*.vue'],
  angular: ['**/*.component.ts', '**/*.component.html'],
  auto: ['**/*.html'],
};

export interface InitAIOptions {
  provider: ProviderId;
  generationModel: string;
  healingModel: string;
  /**
   * API key value entered by the user. When empty AND `useExistingEnv` is
   * true, the server reads the value from its own process.env (so the key
   * never crosses the wire from the browser).
   */
  apiKey: string;
  /** Reuse the env var already set in the server's environment */
  useExistingEnv: boolean;
  /** Override the default endpoint — used for Ollama / DeepSeek / self-hosted */
  baseURL?: string;
}

export interface InitOptions {
  rootDir: string;
  /** 'react' | 'vue' | 'angular' | 'auto' */
  framework: string;
  /** Glob patterns to include — defaults to FRAMEWORK_EXTENSIONS[framework] when empty */
  include: string[];
  testsDir: string;
  baseURL: string;
  /** AI provider configuration */
  ai: InitAIOptions;
}

export interface GenerateResult {
  configContent: string;
  configPath: string;
  /** Reminder message — the actual key is never returned */
  envNote: string;
}

/**
 * Shape of the persisted session stored in `.selfcure/session.json`.
 * Never contains secrets — API key stays in `.env`.
 */
export interface SessionData {
  rootDir: string;
  framework: string;
  include: string[];
  testsDir: string;
  baseURL: string;
  ai: {
    provider: string;
    generationModel: string;
    healingModel: string;
    baseURL?: string;
  };
  savedAt: string;
}

export function buildConfigContent(options: InitOptions): string {
  const { rootDir, framework, include, testsDir, baseURL, ai } = options;
  const safeInclude =
    include.length > 0
      ? include
      : (FRAMEWORK_EXTENSIONS[framework] ?? ['**/*.tsx']);
  const baseURLLine = ai.baseURL ? `\n    baseURL: '${ai.baseURL}',` : '';

  // For HTML/vanilla projects, dist/ is where pages live — don't exclude it.
  // For TS-based frameworks, dist/ is compiled output and should be excluded.
  const excludeDist = framework === 'auto' ? [] : ["'**/dist/**'"];
  const excludeStr = `['**/*.spec.*', '**/*.test.*', '**/node_modules/**'${excludeDist.length ? ", '**/dist/**'" : ''}]`;

  return `\
// selfcure.config.mjs — generated by selfcure init
/** @type {import('@selfcure/cli').SelfcureConfig} */
export default {
  // ── Source crawl ─────────────────────────────────────────────────────────
  rootDir: '${rootDir}',
  include: ${JSON.stringify(safeInclude)},
  exclude: ${excludeStr},
  framework: '${framework}',

  // ── Authentication ────────────────────────────────────────────────────────
  // auth: { type: 'form', loginURL: '/login', ... },

  // ── Browser ──────────────────────────────────────────────────────────────
  browser: {
    type: 'chromium',
    headless: true,
    viewport: { width: 1280, height: 720 },
    timeout: 30_000,
    slowMo: 0,
  },

  // ── AI provider ──────────────────────────────────────────────────────────
  ai: {
    provider: '${ai.provider}',
    generationModel: '${ai.generationModel}',
    healingModel: '${ai.healingModel}',${baseURLLine}
  },

  // ── Test generation ───────────────────────────────────────────────────────
  testsDir: '${testsDir}',
  maxInputTokens: 4096,

  // ── Test execution ────────────────────────────────────────────────────────
  playwrightConfig: './playwright.config.ts',
  baseURL: '${baseURL}',

  // ── Self-healing ──────────────────────────────────────────────────────────
  maxHealAttempts: 3,

  // ── Reporting ─────────────────────────────────────────────────────────────
  reportDir: './selfcure-report',
  reportTitle: 'Selfcure Report',
};
`;
}

/**
 * Write selfcure.config.mjs and .env to {@link cwd}.
 *
 * The API key is resolved server-side:
 *   - if `ai.useExistingEnv` is true → read from this process's env
 *   - otherwise → use the value posted in `ai.apiKey`
 *
 * Ollama (no envVar) skips the .env update entirely.
 *
 * Returns the generated config content (the API key is NEVER included in the
 * return value).
 */
export async function generateConfig(
  options: InitOptions,
  cwd: string,
): Promise<GenerateResult> {
  const configContent = buildConfigContent(options);
  const configPath = path.join(cwd, 'selfcure.config.mjs');

  await fs.outputFile(configPath, configContent, 'utf-8');

  const meta = PROVIDERS[options.ai.provider];
  let envNote = 'No .env update required for this provider.';

  if (meta.envVar) {
    const value = options.ai.useExistingEnv
      ? (process.env[meta.envVar] ?? '')
      : options.ai.apiKey;

    if (value) {
      await upsertEnvVar(path.join(cwd, '.env'), meta.envVar, value);
      envNote = options.ai.useExistingEnv
        ? `.env updated from existing $${meta.envVar} in your environment (value omitted from this response).`
        : `.env written with ${meta.envVar} (value omitted from this response).`;
    } else {
      envNote =
        `No value available for ${meta.envVar}. Set it in your shell or rerun the wizard with a key.`;
    }
  }

  await saveSession(cwd, options);
  await ensureGitignore(cwd, ['.selfcure/', '.env']);

  return {
    configContent,
    configPath,
    envNote,
  };
}

/**
 * Persist wizard state to `.selfcure/session.json` so the form can be
 * pre-filled on subsequent visits. The API key is never stored here.
 */
async function saveSession(cwd: string, options: InitOptions): Promise<void> {
  const sessionPath = path.join(cwd, '.selfcure', 'session.json');
  const data: SessionData = {
    rootDir: options.rootDir,
    framework: options.framework,
    include: options.include,
    testsDir: options.testsDir,
    baseURL: options.baseURL,
    ai: {
      provider: options.ai.provider,
      generationModel: options.ai.generationModel,
      healingModel: options.ai.healingModel,
      ...(options.ai.baseURL ? { baseURL: options.ai.baseURL } : {}),
    },
    savedAt: new Date().toISOString(),
  };
  await fs.outputJson(sessionPath, data, { spaces: 2 });
}

/**
 * Read the persisted session. Returns null when no session exists yet.
 */
export async function loadSession(cwd: string): Promise<SessionData | null> {
  try {
    const sessionPath = path.join(cwd, '.selfcure', 'session.json');
    return (await fs.readJson(sessionPath)) as SessionData;
  } catch {
    return null;
  }
}

/**
 * Delete the persisted session file (called when the user clicks "clear").
 */
export async function clearSession(cwd: string): Promise<void> {
  const sessionPath = path.join(cwd, '.selfcure', 'session.json');
  try {
    await fs.remove(sessionPath);
  } catch { /* non-fatal */ }
}

/**
 * Check whether a given env var is present (non-empty) in the `.env` file on
 * disk — without relying on `process.env` which may not have loaded the file.
 */
export async function envKeyIsSet(cwd: string, key: string): Promise<boolean> {
  try {
    const content = await fs.readFile(path.join(cwd, '.env'), 'utf-8');
    return new RegExp(`^${key}=.+`, 'm').test(content);
  } catch {
    return false;
  }
}

/**
 * Ensure `.gitignore` in `cwd` contains every entry in `entries`.
 * Entries already present (exact match, ignoring trailing slash variants) are
 * skipped so the file is not modified unnecessarily.
 */
async function ensureGitignore(cwd: string, entries: string[]): Promise<void> {
  const gitignorePath = path.join(cwd, '.gitignore');
  let content = '';
  try {
    content = await fs.readFile(gitignorePath, 'utf-8');
  } catch { /* file doesn't exist yet — fine */ }

  const lines = content.split('\n').map((l) => l.trim());
  const toAdd = entries.filter((entry) => {
    const bare = entry.replace(/\/$/, '');
    return !lines.includes(entry) && !lines.includes(bare) && !lines.includes(bare + '/');
  });

  if (toAdd.length === 0) return;

  const sep = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
  await fs.outputFile(
    gitignorePath,
    content + sep + '\n# selfcure\n' + toAdd.join('\n') + '\n',
    'utf-8',
  );
}

/**
 * Update or append a KEY=value line in a .env file without clobbering other
 * existing entries.
 */
async function upsertEnvVar(envPath: string, key: string, value: string): Promise<void> {
  let existing = '';
  try {
    existing = await fs.readFile(envPath, 'utf-8');
  } catch {
    // file doesn't exist yet — fine
  }

  const lineRegex = new RegExp(`^${key}=.*$`, 'm');
  const newLine = `${key}=${value}`;
  const updated = lineRegex.test(existing)
    ? existing.replace(lineRegex, newLine)
    : (existing.endsWith('\n') || existing === '' ? existing : existing + '\n') + newLine + '\n';

  await fs.outputFile(envPath, updated, 'utf-8');
}
